# Generated by Django 4.1 on 2022-08-22 07:12

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', max_length=255, unique=True)),
                ('email', models.EmailField(db_column='email', max_length=255, unique=True)),
                ('password', models.CharField(db_column='password', max_length=255)),
                ('is_staff', models.BooleanField(default=False)),
                ('address', models.CharField(db_column='address', max_length=255, null=True)),
                ('contact', models.BigIntegerField(db_column='contact', null=True)),
                ('bankadmin', models.CharField(db_column='bankadmin', max_length=255, null=True)),
                ('account_number', models.BigIntegerField(db_column='account_NO', null=True, unique=True)),
                ('ifsc', models.CharField(default='ABC00012', max_length=255, null=True)),
                ('pin_number', models.IntegerField(db_column='pin_no', null=True)),
                ('account_type', models.CharField(db_column='account_type', max_length=255, null=True)),
            ],
            options={
                'db_table': 'user_table',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserAccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(db_column='debit', decimal_places=2, default=0, max_digits=12, null=True)),
                ('credit', models.DecimalField(db_column='credit', decimal_places=2, default=0, max_digits=12, null=True)),
                ('balance', models.DecimalField(db_column='balance', decimal_places=2, default=0, max_digits=12, null=True)),
                ('amount', models.DecimalField(db_column='amount', decimal_places=2, default=0, max_digits=12, null=True)),
                ('trans_id', models.DecimalField(db_column='trans_account_no', decimal_places=2, default=0, max_digits=12, null=True)),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_account_table',
            },
        ),
        migrations.CreateModel(
            name='BalanceViewModel',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('balance', models.DecimalField(db_column='amount', decimal_places=2, default=0, max_digits=12, null=True)),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_balance_table',
            },
        ),
    ]
