# Generated by Django 4.1 on 2022-08-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='block',
            field=models.BooleanField(db_column='block_user', default=False),
        ),
    ]
